### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by titilambert** [jlpk/joulupukki-api#1]
- [ ] User documentation
- [ ] Add Doc String for all functions
- [ ] Replace "repos" term by "projects" 
  - "repos" term will be used as deb/rpm repositories
- [ ] Fix all API return to use JSON as return
